### PR TITLE
TRAIN#34 - Dates Not Saving On Safari

### PR DESCRIPTION
**Pull request by kodinkat**
- fixes: #34

### CODE REVIEW

**Comment by corsacca** [comment]
@kodinkat 
Jan 2 at 8am:
image

Produces:
Jan 2 at 2pm
image

(I did set my timezone to chicago... :)

**Comment by kodinkat** [comment]
> @kodinkat Jan 2 at 8am: image
> 
> Produces: Jan 2 at 2pm image
> 
> (I did set my timezone to chicago... :)

@corsacca 

Unable to recreate, following wp-timezone change; as timestamps remained in-sync from picker to side activity comment.

FYI - [toISOString()](https://momentjs.com/docs/#/displaying/as-iso-string/) function, with offset set to false, should return timestamps in UTC format.

Screenshot 2024-01-19 at 12 48 09

Screenshot 2024-01-19 at 12 49 05

**Comment by corsacca** [comment]
@kodinkat Set your system (Operating system) to a different time zone. Quit your browser and open again.
Then try testing again.

**Comment by kodinkat** [comment]
> @kodinkat Set your system (Operating system) to a different time zone. Quit your browser and open again. Then try testing again.

@corsacca let me know how the latest tweak holds up for you, across the various timezones....

**Comment by corsacca** [comment]
@kodinkat the epoch timestamp without the offset is the correct way to go.
The issue here is that the activity isn't formatted correctly.
The other date fields return a timestamp, and then gets converted locally with the browser's timezone. 
Lets make this activity match the others.

image

**Comment by corsacca** [comment]
Thanks @kodinkat
Activity only shows the date, todo for sometime is upgrading it to show date and time.
Time is shown on the date series itself, so there is good.

**Pull request merged**
